---
title: "m12exercises"
author: "Qais Youssef"
date: "2024-07-09"
output: pdf_document
---
## 12.1


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(dplyr)
library(ggplot2)
library(vctrs)
head(mpg)
mpg %>%
  ggplot()
```
## 12.2
```{r}
mpg %>% ggplot(aes(x=cyl,y=hwy)) + geom_point()
```

## 12.3

```{r}
mpg %>% ggplot(aes(x=class,y=drv)) + geom_point()
```

Presence of combinations, not their frequency.
## 12.4

```{r}
x <- seq(-6*pi,6*pi,length.out = 100)
df <- data.frame(x = x, y = sin(x)/x)
ggplot(df,aes(x=x,y=y)) + geom_line()
```

## 12.5

```{r}
cars %>% ggplot(aes(x=speed,y=dist)) + geom_point()
```

## 12.6

```{r}
cars %>% 
  ggplot(aes(x=speed,y=dist,color = dist > 80)) + geom_point()
```

## 12.7

```{r}
cars %>% 
  ggplot(aes(x=speed,y=dist,color = dist > 80)) + 
  geom_point() + 
  scale_color_manual(values=("cyan",'red'))
```

## 12.8

```{r}
cars %>% 
  ggplot(aes(x=speed,y=dist)) + 
  geom_point(aes(color = dist > 80)) + 
  scale_color_manual(values=c("blue",'red')) + 
  geom_smooth(method = 'lm')
```

## 12.9

```{r}
cars %>% 
  ggplot(aes(x=speed)) +
  geom_histogram(bins=10)
```

```{r}
cars %>% 
  ggplot(aes(x=dist)) +
  geom_histogram(bins=10)
```

## 12.10

```{r}
mpg %>%
  ggplot() +
  geom_point(aes(x=hwy,y=cty)) +
  facet_grid(drv ~ cyl)
```

## 12.11

```{r}
iris %>% 
  ggplot(
    aes(x=Sepal.Length,y=Sepal.Width,
    color=Species, shape=Species)
    ) +
  geom_point() +
  geom_density2d() +
  ggtitle("IRIS")
  theme_light()
```
